channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - matplotlib=3.9.2
  - networkx=3.2.1
  - numba=0.60.0
  - opencv=4.10.0
  - pillow=11.0.0
  - protobuf=5.28.2
  - psutil=6.1.0
  - py-opencv=4.10.0
  - pytest=8.3.3
  - python=3.9.20
  - pytorch=2.4.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing_extensions=4.12.2
  - wandb=0.13.1
  - pip:
    - configargparse==1.7
    - einops==0.8.0
    - h5py==3.12.1
    - lightning-utilities==0.11.8
    - markdown==3.7
    - numpy==1.26.4
    - pandas==2.2.3
    - positional-encodings==6.0.3
    - pytz==2024.2
    - seaborn==0.13.2
    - torchmetrics==1.5.1
    - tzdata==2024.2
    - werkzeug==3.0.6
    - wrapt==1.16.0
    - scikit-learn==1.5.2
    - x-transformers==1.40.6

