# load from the base file
base: ../base.yml


requirements:
  loader_args:
    bs_ood: 100  # extra loader arguments


method:
  name: repulsive_kernel
  num: 5
  gamma: 1.0
  gamma_ood: 5.0
  warmup: 300  # warmup he/repulsive term
  beta_ind: 1.5
  beta_ood: 0.0
  learnable: true

  ind_loss:
    name: cross_entropy
  # ood_loss:
  #   name: mean_softmax_entropy
  
  model_kernel:
    name: model_layers
    layer_kernel:
      name: he
      eps: 0.0025
      arc_eps: 0.15
      learnable: true
      feature_kernel:
        name: feature
        detach_diag: true
        kernel: linear
    layer_weighting:
      name: tensor
      weights: 5  # 4 layers
      learnable: true
    # layer_weighting:
    #   name: start_end_linear
    #   first_layer: 0.05
    #   middle_start: 0.25
    #   middle_increase: 1.25
    #   last_layer: 3.0


trainer:
  ood_N: 100
  learn_hyper: true  # learn repulsive kernel hyperparameters
  learn_hyper_loss:  # hyperparameter loss
    name: inlier_outlier_entropy
    weight: 0.8
  metrics:
    - name: accuracy
      classes: 10
    - name: ckas