# load from the base file
base: ../base.yml


method:
  name: svgd
  num: 5
  model_kernel:
    name: model_layers
    reduction: none
    layer_kernel:
      name: he
      eps: 0.00005
      arc_eps: 0.165
      detach_right: true
      reduction: none
      feature_kernel:
        name: feature
        detach_diag: true
        kernel: cossim
    layer_weighting:
      name: start_end_linear
      first_layer: 0.0  # 0.029
      middle_start: 0.5  # 0.587
      middle_increase: 1.75  # 1.80
      last_layer: 6.5  # 6.833

  ind_loss:
    name: cross_entropy


trainer:
  metrics:
    - name: accuracy
      classes: 10
