# load from the base file
base: ../base.yml


# specify the method to use
# available are basic (no repulsive), svgd, ensemble
method:
  name: function_svgd
  num: 30
  kde: true
  eta: 0.02
  exp_std: 0.115
  model_kernel:
    name: function
    detach_right: true
    kernel: rbf
  ind_loss:
    name: cross_entropy

trainer:
  optim_args:
    lr: 0.0075
  metrics:
    - name: accuracy
      classes: 4