# load from the base file
base: ../base.yml


method:
  name: repulsive_kernel
  num: 5
  gamma: 6.35  # 6.34
  warmup: 50  # 300  # warmup he/repulsive term
  model_kernel:
    name: model_layers
    layer_kernel:
      name: he
      eps: 0.0025
      arc_eps: 0.065  # 0.0655
      feature_kernel:
        name: feature
        detach_diag: true
        kernel: cossim
        # params:
        #   param: 1.0
    layer_weighting:
      name: start_end_linear
      first_layer: 0.03  # 0.029
      middle_start: 0.60  # 0.587
      middle_increase: 1.80  # 1.81
      last_layer: 6.8  # 3.0

  ind_loss:
    name: cross_entropy


trainer:
  metrics:
    - name: accuracy
      classes: 10
    - name: ckas