# load from the base file
base: ../base.yml


method:
  name: repulsive_kernel
  num: 5
  # gamma: 7.15
  gamma: 10.5
  warmup: 600  # warmup he/repulsive term
  model_kernel:
    name: model_layers
    # layer_kernel:
    #   name: he
    #   eps: 0.0025
    #   arc_eps: 0.10
    #   feature_kernel:
    #     name: feature
    #     detach_diag: true
    #     kernel: linear
    # layer_weighting:
    #   name: start_end_linear
    #   first_layer: 0.25
    #   middle_start: 0.5
    #   middle_increase: 1.0
    #   last_layer: 3.0

    layer_kernel:
      name: he
      eps: 0.0025
      arc_eps: 0.031
      feature_kernel:
        name: feature
        detach_diag: true
        kernel: linear
    layer_weighting:
      name: start_end_linear
      first_layer: 0.387
      middle_start: 0.746
      middle_increase: 1.267
      last_layer: 3.63

  ind_loss:
    name: cross_entropy


trainer:
  metrics:
    - name: accuracy
      classes: 10
    - name: ckas