# load from the base file
base: ../base.yml


method:
  name: repulsive_kernel
  num: 5
  gamma: 6.34  # 3.0
  warmup: 50  # 300  # warmup he/repulsive term
  model_kernel:
    name: model_layers
    layer_kernel:
      name: he
      eps: 0.0025
      arc_eps: 0.0655  # 0.15
      feature_kernel:
        name: feature
        detach_diag: true
        kernel: rbf
        params:
          param: 1.0
    layer_weighting:
      name: start_end_linear
      first_layer: 0.029  # 0.05
      middle_start: 0.587  # 0.25
      middle_increase: 1.81  # 1.25
      last_layer: 6.833  # 3.0

  ind_loss:
    name: cross_entropy


trainer:
  metrics:
    - name: accuracy
      classes: 10
    - name: ckas