# load from the base file
base: ../base.yml


method:
  name: svgd
  num: 30
  model_kernel:
    name: model_layers
    reduction: none
    layer_kernel:
      name: he
      eps: 0.00025
      arc_eps: 0.03
      detach_right: true
      reduction: none
      feature_kernel:
        name: feature
        detach_diag: true
        kernel: cossim
    layer_weighting:
      name: list
      weights: [0.2, 0.35, 0.85, 0.05]


  ind_loss:
    name: cross_entropy


trainer:
  metrics:
    - name: accuracy
      classes: 4