# load from the base file
base: ../base.yml


method:
  name: repulsive_kernel
  num: 30
  gamma: 7.5
  warmup: 0.0035
  beta_ind: 2.25  # weighting for inlier
  model_kernel:
    name: model_layers
    layer_kernel:
      name: he
      he_s: 5.0
      eps: 0.000005
      arc_eps: 0.00305
      feature_kernel:
        name: feature
        detach_diag: true
        kernel: rbf
        params:
          param: 5.025
    layer_weighting:
      name: list
      weights: [0.05, 0.35, 1.0, 0.85]


  ind_loss:
    name: cross_entropy


trainer:
  metrics:
    - name: accuracy
      classes: 4
    - name: ckas
